# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- PR


jobs:
# download piper and put it into cache
- job: downloadPiper
  dependsOn: runUnitTests
  pool:
    vmImage: 'ubuntu-latest'
  container:
    image: ppiper/cf-cli
    options: -u 0
  steps:
  - checkout: none
  # check cache for piper
  - task: Cache@2
    inputs:
      key: piper-go-official
      path: bin
      cacheHitVar: FOUND_PIPER
    displayName: Cache piper go binary
  # download if piper not in cache
  - script: |
        mkdir -p bin
        curl -L --output bin/piper https://github.com/SAP/jenkins-library/releases/download/v1.73.0/piper
        chmod +x bin/piper
    condition: ne(variables.FOUND_PIPER, 'true')
    displayName: 'Download Piper'
  - script: bin/piper version
    displayName: 'Piper Version'

# Unit Tests
- job: runUnitTests
  pool:
    vmImage: 'ubuntu-latest'  
  container:
    image: markadams/chromium-xvfb-js
  steps:
  - script: |      
      npm i chromedriver --chromedriver_version=LATEST --save-dev  
      export CHROME_BIN='/usr/bin/chromium'
      npm install
      npm test    
    workingDirectory: HTML5Module
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/TEST-RESULTS.xml'

# build piper mta and publish artifact
- job: piperMta
  dependsOn: downloadPiper
  pool:
    vmImage: 'ubuntu-latest'
  container:
    image: devxci/mbtci
    options: -u 0
  steps:
  
  # get binary from cache
  - task: Cache@2
    inputs:
      key: piper-go-official
      path: bin
    displayName: resolve piper go binary from cache
  # build mta
  - script: |
      bin/piper version
      bin/piper mtaBuild
    displayName: 'Perform mta build'  
  
 
  # publish artifact 
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(System.DefaultWorkingDirectory)/BAS_Sample_App.mtar
      artifactName: mtar
    displayName: 'Publish mtar'



